# /etc/nsswitch.conf: GNU C Library name service switch.
passwd:  files
group:   files
shadow:  files
hosts:   files dns
networks: files
protocols: files
services: files
ethers:  files
rpc:     files
shells:  files
