#!/usr/bin/env bash
# Resolve the transitive .deb closure for the sidekick's Debian tool set
# against a pinned snapshot.debian.org timestamp, and regenerate the
# `debian` block of packages.nix (name → {version, filename, sha256}).
#
# The snapshot Packages index already carries each .deb's Filename +
# SHA256, so we don't download/hash anything here — we parse the index,
# BFS the dependency closure from the top-level set, and emit the pins.
# The nix build (default.nix) then fetchurl's each .deb from the snapshot
# by that URL + hash — reproducible forever (snapshot archives every
# version, unlike Alpine edge).
#
# Usage:  flakes/sidekick/refresh-packages.sh [SNAPSHOT] > /tmp/debian-pkgs.nix
#   then fold the output into packages.nix.  Re-run to bump the snapshot.
#
# Needs: curl + python3 (both on stock macOS / any dev box).  No apt/dpkg,
# no xz binary (python's lzma handles decompression).
set -euo pipefail

SNAPSHOT="${1:-20260515T000000Z}"
SUITE="${SUITE:-bookworm}"
ARCH="${ARCH:-amd64}"

# Top-level tools the VM must provide.  These are the operations that run
# INSIDE the VM (Linux-kernel ops + Linux-only tools), so their tools must
# be present here regardless of nix-on-darwin availability:
#   busybox                  agent basics (sh/mount/insmod/awk/…)
#   abigail-tools, pahole    the ABI gate's Tier-2 + pahole analysers
#   grub-pc-bin, grub-common grub-mkrescue (mkiso op)
#   xorriso, mtools          grub-mkrescue's ISO + EFI-FAT helpers (in-VM)
#   e2fsprogs                ext fsck/tools for the overlay-kernel op
# Their transitive Depends pull in libc6/libstdc++6/libxml2/libdw1/… .
# NOT bundled: abi-compliance-checker (probe 23) — it's a perl-based
# confirmatory cross-check that would ~2x the image; abidiff is the
# authority for type/struct ABI, so probe 23 stays an opt-in skip (add
# abi-compliance-checker + abi-dumper here to enable it).
TOPLEVEL="${TOPLEVEL:-busybox abigail-tools pahole grub-pc-bin grub-common xorriso mtools e2fsprogs}"

BASE="https://snapshot.debian.org/archive/debian/${SNAPSHOT}"
IDX="${BASE}/dists/${SUITE}/main/binary-${ARCH}/Packages.xz"

echo "# resolving against ${IDX}" >&2
curl -sSL "$IDX" -o /tmp/.sk-Packages.xz

SNAPSHOT="$SNAPSHOT" SUITE="$SUITE" ARCH="$ARCH" TOPLEVEL="$TOPLEVEL" \
python3 - <<'PY'
import lzma, os, re, sys

snapshot = os.environ["SNAPSHOT"]; toplevel = os.environ["TOPLEVEL"].split()
raw = lzma.open("/tmp/.sk-Packages.xz", "rt", encoding="utf-8", errors="replace").read()

# Parse stanzas into pkg -> fields.  Also build a Provides map (virtual
# package -> a concrete provider) so deps on virtuals resolve.
pkgs, provides = {}, {}
for stanza in raw.split("\n\n"):
    if not stanza.strip():
        continue
    f = {}
    key = None
    for line in stanza.split("\n"):
        if line[:1] in (" ", "\t"):
            continue
        if ":" in line:
            key, _, val = line.partition(":")
            f[key.strip()] = val.strip()
    name = f.get("Package")
    if not name:
        continue
    pkgs[name] = f
    for prov in re.split(r"\s*,\s*", f.get("Provides", "")):
        prov = re.sub(r"\s*\(.*\)", "", prov).strip()
        if prov:
            provides.setdefault(prov, name)

def dep_names(field):
    """Yield the chosen package for each Depends/Pre-Depends clause.
    Alternatives 'a | b' -> first that exists; strip version constraints;
    fall back to a Provides provider for virtuals."""
    for clause in re.split(r"\s*,\s*", field):
        clause = clause.strip()
        if not clause:
            continue
        chosen = None
        for alt in re.split(r"\s*\|\s*", clause):
            nm = re.sub(r"\s*[\(\[<].*", "", alt).strip()
            if nm in pkgs:
                chosen = nm; break
            if nm in provides:
                chosen = provides[nm]; break
        if chosen:
            yield chosen

# BFS closure.
seen, queue = set(), list(toplevel)
while queue:
    nm = queue.pop()
    if nm in seen:
        continue
    if nm not in pkgs:
        nm = provides.get(nm)
        if not nm or nm in seen:
            continue
    seen.add(nm)
    f = pkgs[nm]
    for field in ("Pre-Depends", "Depends"):
        if field in f:
            for d in dep_names(f[field]):
                if d not in seen:
                    queue.append(d)

missing = [t for t in toplevel if t not in pkgs and t not in provides]
if missing:
    sys.stderr.write(f"WARNING: top-level not found in index: {missing}\n")

base = f"https://snapshot.debian.org/archive/debian/{snapshot}"
print(f"# Generated by refresh-packages.sh — snapshot {snapshot}, {os.environ['SUITE']}/{os.environ['ARCH']}.")
print(f"# {len(seen)} packages (closure of: {' '.join(toplevel)}).")
print("{")
print(f'  snapshot = "{snapshot}";')
print(f'  suite = "{os.environ["SUITE"]}"; arch = "{os.environ["ARCH"]}";')
print('  packages = {')
for nm in sorted(seen):
    f = pkgs[nm]
    fn, sha, ver = f.get("Filename"), f.get("SHA256"), f.get("Version")
    if not (fn and sha):
        sys.stderr.write(f"WARNING: {nm} missing Filename/SHA256\n"); continue
    # nix attr names with '+'/'.' must be quoted.
    print(f'    "{nm}" = {{ version = "{ver}"; sha256 = "{sha}"; url = "{base}/{fn}"; }};')
print("  };")
print("}")
sys.stderr.write(f"resolved {len(seen)} packages\n")
PY
